#!/usr/bin/with-contenv sh

[ -f /config/hetzner.conf ] || exit 0

. /app/hetzner.sh
. /config/hetzner.conf

if [ "$DELETE_ON_STOP" == "true" ]; then
  echo "Deleting Hetzner DNS Console record $HETZNER_RECORD_NAME..."

  update=$(deleteDnsRecord $HETZNER_RECORD_ID)

  if [ "$update" == "null" ]; then
    echo "ERROR: Failed to delete Hetzner DNS Console record $HETZNER_RECORD_NAME"
  else
    echo "Hetzner DNS Console record $HETZNER_RECORD_NAME deleted successfully."
  fi
else
  echo "Not going to delete zone record. Deleting the zone record on container stop is disable by default."
fi