#!/usr/bin/with-contenv sh

. /app/hetzner.sh
. /config/hetzner.conf

DnsIpAddress=$(getDnsRecordIp $HETZNER_RECORD_ID)

if [ ! -z ${CUSTOM_LOOKUP_CMD+x} ]; then
  CurrentIpAddress=$(getCustomIpAddress)
elif [ ! -z ${INTERFACE+x} ]; then
  CurrentIpAddress=$(getLocalIpAddress)
else
  CurrentIpAddress=$(getPublicIpAddress)
fi

if [ "$CurrentIpAddress" != "$DnsIpAddress" ]; then
  echo "Updating Hetzner DNS Console record $HETZNER_RECORD_NAME from $DnsIpAddress to $CurrentIpAddress..."
  update=$(updateDnsRecord $HETZNER_ZONE_ID $HETZNER_RECORD_ID $HETZNER_RECORD_NAME $CurrentIpAddress)

  if [ "$update" == "null" ]; then
    echo "ERROR: Failed to update Hetzner DNS Console record $HETZNER_RECORD_NAME from $DnsIpAddress to $CurrentIpAddress"
  else
    echo "Hetzner DNS Console record $HETZNER_RECORD_NAME ($CurrentIpAddress) updated successfully."
  fi
  
else
  echo "No DNS update required for $HETZNER_RECORD_NAME ($DnsIpAddress)."
fi